### ISSUE TITLE
Was playing ArkSE and it crashed after restarting ArkSE I tabbed to Larkator to find the app has an all whit screen, other than the title bar.

### ISSUE THREAD

**Issue by mrcomptech** [coldino/Larkator#82]
Crash dump immediately after clicking the close button in the upper right window corner.

---------------------------
Whoops...
---------------------------
Sorry, something bad happened and the application must exit.

If you wish to report this issue please press Ctrl-C now to copy the details and

paste it into a new issue along with a description of what was happening

at: https://github.com/coldino/Larkator/issues

Thanks!

Exception:

System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)

   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()

   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)

   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)

   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

---------------------------
OK   
---------------------------

**Comment by coldino** [comment]
For now I'll have to assume something odd with your driver setup or hardware reliability. [This document from Microsoft](https://docs.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures) says:
> The most common bucket of WPF render thread failures is associated with video hardware or driver problems.

...and that seems to be backed up other references I see to similar error reports elsewhere.
